#line 2 "lexique.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
static yyconst short int yy_acclist[377] =
    {   0,
       55,   53,   54,    1,   53,   54,    1,   54,    1,   53,
       54,   36,   53,   54,   53,   54,   33,   53,   54,   32,
       53,   54,   35,   53,   54,   34,   53,   54,    2,   53,
       54,   43,   53,   54,   40,   53,   54,   31,   53,   54,
       39,   53,   54,   51,   53,   54,   51,   53,   54,   51,
       53,   54,   51,   53,   54,   51,   53,   54,   51,   53,
       54,   51,   53,   54,   51,   53,   54,   51,   53,   54,
       51,   53,   54,   51,   53,   54,   51,   53,   54,   51,
       53,   54,   51,   53,   54,   51,   53,   54,   51,   53,
       54,   51,   53,   54,   51,   53,   54,   51,   53,   54,

       51,   53,   54,   51,   53,   54,   51,   53,   54,   51,
       53,   54,   51,   53,   54,   51,   53,   54,   51,   53,
       54,   51,   53,   54,   51,   53,   54,   53,   54,   53,
       54,    5,    2,   42,   30,   29,   41,   51,   51,   51,
       51,   51,   51,   51,   51,   37,   51,   51,   51,   51,
       51,   51,   51,   38,   51,   51,   51,   51,   51,   51,
       18,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       18,   51,   51,   51,   51,   52,    4,    3,    6,   51,
       51,   51,   51,   51,   22,   51,   51,   51,   51,   51,

       50,   51,   51,   25,   51,   51,   51,   51,   51,   24,
       51,   51,   51,   51,   51,   14,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   50,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   10,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   44,   51,   26,   51,   51,    9,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,    7,   51,   51,   20,   51,   12,   51,   13,
       51,   49,   51,   51,   51,   17,   51,   51,   51,   21,

       51,   51,   51,   51,   51,   51,   19,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,    8,   51,   45,   51,   23,   51,   51,   51,   51,
       51,   51,   11,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   27,   51,   51,   51,   51,   51,   15,
       51,   51,   51,   51,   51,   51,   51,   51,   46,   51,
       51,   28,   51,   51,   51,   51,   51,   51,   47,   51,
       51,   51,   48,   51,   16,   51
    } ;

static yyconst short int yy_accept[269] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   17,
       20,   23,   26,   29,   32,   35,   38,   41,   44,   47,
       50,   53,   56,   59,   62,   65,   68,   71,   74,   77,
       80,   83,   86,   89,   92,   95,   98,  101,  104,  107,
      110,  113,  116,  119,  122,  125,  128,  130,  132,  132,
      133,  133,  134,  134,  135,  136,  137,  138,  139,  139,
      140,  141,  142,  143,  144,  145,  146,  148,  149,  150,
      151,  152,  153,  154,  156,  157,  158,  159,  160,  161,
      163,  164,  165,  166,  167,  168,  169,  170,  171,  172,
      173,  174,  175,  176,  177,  178,  179,  180,  181,  183,

      184,  185,  186,  186,  187,  188,  189,  189,  190,  191,
      192,  193,  194,  195,  197,  198,  199,  200,  201,  203,
      204,  206,  207,  208,  209,  210,  212,  213,  214,  215,
      216,  218,  219,  220,  221,  222,  223,  224,  225,  226,
      227,  229,  230,  231,  232,  233,  234,  235,  236,  237,
      238,  239,  240,  241,  242,  244,  245,  246,  247,  248,
      249,  250,  251,  252,  253,  254,  256,  258,  259,  261,
      262,  263,  264,  265,  266,  267,  268,  269,  270,  271,
      272,  273,  274,  275,  276,  277,  278,  279,  280,  281,
      282,  283,  285,  286,  288,  290,  292,  294,  295,  296,

      298,  299,  300,  302,  303,  304,  305,  306,  307,  309,
      310,  311,  312,  313,  314,  315,  316,  317,  318,  319,
      320,  321,  322,  324,  326,  328,  329,  330,  331,  332,
      333,  335,  336,  337,  338,  339,  340,  341,  342,  343,
      344,  346,  347,  348,  349,  350,  352,  353,  354,  355,
      356,  357,  358,  359,  361,  362,  364,  365,  366,  367,
      368,  369,  371,  372,  373,  375,  377,  377
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    5,    5,    7,    5,    8,    5,
        5,    9,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    5,   15,   16,
       17,   18,    5,    5,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   29,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   29,   29,   29,   29,
       40,    5,   41,    5,    5,    5,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   29,   29,
       64,   29,   65,   66,   67,    1,    1,    5,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[68] =
    {   0,
        1,    2,    2,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    4,    3,    3,    3,    3,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    4,
        3,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1,    2
    } ;

static yyconst short int yy_base[272] =
    {   0,
        0,    0,  558,  559,  559,  559,  551,  559,    0,  559,
      542,  541,  559,   56,  559,   54,  537,  536,   29,   33,
       48,   35,   47,   43,  512,   39,   36,   56,   49,   72,
       60,   61,   79,   62,   64,   71,   76,   77,   84,   66,
       85,   74,   91,   89,   67,   96,  484,  536,  543,  542,
      539,  129,  532,  559,  559,  559,  559,  505,  128,  104,
      105,  127,  116,  108,  114,  118,  504,  113,  109,  121,
      122,  130,  123,  503,  124,  125,  150,  134,  140,  138,
      139,  152,  148,  145,  155,  157,  158,  160,  161,  144,
      162,  166,  167,  168,  170,  169,  171,  177,  178,  176,

      184,  179,  475,  559,  559,  527,  211,  559,  174,  186,
      200,  208,  210,  500,  196,  217,  197,  209,  230,  215,
      499,  214,  213,  221,  234,  498,  216,  235,  229,  231,
      497,  233,  236,  238,  237,  241,  242,  243,  244,  246,
      258,  247,  257,  248,  266,  259,  250,  260,  271,  268,
      269,  274,  277,  280,  496,  285,  283,  301,  286,  288,
      296,  287,  299,  300,  291,  495,  494,  307,  493,  295,
      315,  308,  316,  314,  317,  318,  319,  320,  324,  321,
      322,  329,  326,  325,  332,  336,  338,  339,  345,  346,
      347,  492,  348,  491,  490,  489,  488,  354,  350,  487,

      351,  352,  486,  353,  359,  362,  363,  379,  485,  366,
      370,  372,  373,  375,  376,  381,  383,  377,  384,  386,
      385,  389,  484,  483,  482,  390,  391,  397,  399,  400,
      471,  405,  401,  404,  403,  402,  414,  419,  420,  428,
      470,  433,  415,  416,  429,  468,  431,  432,  434,  438,
      439,  441,  442,  459,  445,  454,  446,  443,  447,  456,
      461,  452,  463,  466,  444,  417,  559,  510,  166,  512,
      516
    } ;

static yyconst short int yy_def[272] =
    {   0,
      267,    1,  267,  267,  267,  267,  268,  267,  269,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  271,  267,  268,  268,
      267,  267,  267,  267,  267,  267,  267,  270,  267,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  271,  267,  267,  267,  267,  267,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,    0,  267,  267,  267,
      267
    } ;

static yyconst short int yy_nxt[627] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,   10,   11,
       12,    4,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   25,   25,   26,   25,   27,
       25,   28,   29,   25,   30,   31,   32,   25,   33,    4,
        4,   34,   35,   36,   37,   38,   39,   25,   25,   25,
       40,   25,   41,   25,   25,   25,   42,   25,   43,   44,
       45,   25,   46,   25,   47,   48,    4,   53,   59,   52,
       54,   55,   59,   62,   59,   59,   72,   66,   59,   63,
       65,   60,   59,   67,   69,   73,   59,   59,   59,   64,
       68,   61,   70,   74,   77,   59,   79,   82,   71,   59,

       59,   59,   81,   59,   75,   59,   59,   76,  101,   80,
       59,   59,   85,   59,   83,   59,   59,   78,   59,   86,
       89,   88,   84,   59,   59,   91,   87,   94,   59,   96,
       59,   90,   97,   92,   95,   59,   98,  102,   99,   93,
       53,  107,   52,   59,   59,  112,  113,   59,   59,  100,
      111,  109,   59,   59,  116,   59,  115,   59,  118,  110,
       59,   59,   59,   59,   59,  121,   59,  114,  108,   59,
       51,  117,  125,   59,  128,  119,  120,   59,   59,   59,
      124,  122,  126,   59,   59,  123,  131,   59,  127,   59,
      134,   59,  129,  130,   59,  132,   59,   59,  135,   59,

       59,   59,  137,  133,  139,   59,   59,   59,   59,   59,
       59,  140,  136,   59,  114,   59,   59,   59,   59,  138,
      141,  142,  146,   59,  107,   59,  145,  121,  143,  152,
      144,  147,  148,  126,  149,   59,   59,  131,  150,   59,
      151,  154,  155,  158,  153,  156,  159,   59,   59,   59,
      161,  108,   59,   59,   59,   59,   59,  157,  165,  166,
       59,  171,  162,  169,  168,  163,  164,  160,   59,   59,
       59,  167,   59,   59,   59,   59,   59,   59,  170,  176,
       59,   59,   59,   59,  172,   59,   59,   59,  174,   59,
      186,  173,  179,  180,  175,  155,   59,   59,   59,   59,

      177,  182,  166,  178,  181,   59,  167,   59,   59,  187,
       59,  169,  188,   59,  183,  189,   59,  184,  185,   59,
      190,  196,   59,  198,   59,   59,   59,   59,  191,  192,
       59,  195,  193,  200,   59,   59,  194,  201,   59,   59,
       59,  204,  202,  197,  199,  208,   59,   59,  203,  210,
      207,  205,  206,   59,   59,   59,   59,   59,   59,   59,
       59,   59,  209,   59,   59,   59,  213,  200,   59,  195,
      214,   59,  211,  216,  203,   59,  194,   59,   59,  196,
      197,  215,  212,  218,   59,   59,   59,   59,  223,   59,
       59,   59,   59,   59,  219,  224,  217,  222,   59,  209,

      220,   59,   59,  231,  221,   59,  229,  227,  228,   59,
      225,   59,   59,  226,   59,   59,   59,  224,   59,  233,
       59,  237,   59,   59,   59,   59,  230,  232,   59,   59,
       59,  223,  236,  231,  225,  235,   59,  234,   59,   59,
       59,   59,   59,   59,   59,  245,  239,  238,  241,  240,
      246,  242,  243,   59,   59,   59,   59,  249,   59,   59,
      244,  247,  241,  248,  251,  246,  253,   59,   59,  254,
       59,   59,   59,   59,  255,  250,  252,   59,   59,  257,
       59,   59,   59,   59,   59,   59,   59,  256,  254,  258,
      262,   59,  262,   59,  260,   59,  259,  256,   59,  263,

       59,  265,   59,  261,  264,   59,  266,   59,  265,   59,
       59,  266,   49,   49,   49,   58,   58,  103,  103,  103,
      103,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
      106,  104,   59,   59,   59,  106,  105,   50,   50,   52,
      104,   59,   57,   56,   52,   52,   50,  267,    3,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,

      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267
    } ;

static yyconst short int yy_chk[627] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   14,   19,   14,
       16,   16,   20,   21,   22,   27,   26,   23,   26,   21,
       22,   19,   24,   23,   24,   27,   23,   21,   29,   21,
       23,   20,   24,   28,   30,   28,   31,   33,   24,   31,

       32,   34,   32,   35,   29,   40,   45,   29,   45,   31,
       36,   30,   36,   42,   34,   37,   38,   30,   33,   36,
       38,   37,   35,   39,   41,   39,   36,   40,   44,   42,
       43,   38,   42,   39,   41,   46,   43,   46,   44,   39,
       52,   59,   52,   60,   61,   62,   63,   64,   69,   44,
       61,   60,   68,   65,   66,   63,   65,   66,   69,   60,
       70,   71,   73,   75,   76,   72,   62,   64,   59,   72,
      269,   68,   77,   78,   79,   70,   71,   80,   81,   79,
       76,   73,   77,   90,   84,   75,   82,   83,   78,   77,
       84,   82,   80,   81,   85,   83,   86,   87,   86,   88,

       89,   91,   88,   83,   90,   92,   93,   94,   96,   95,
       97,   91,   87,  109,   85,  100,   98,   99,  102,   89,
       92,   93,   98,  101,  107,  110,   97,   94,   95,  109,
       96,   98,   99,   98,  100,  115,  117,  102,  101,  111,
      102,  111,  112,  116,  110,  113,  117,  112,  118,  113,
      119,  107,  123,  122,  120,  127,  116,  115,  120,  122,
      124,  128,  119,  125,  124,  119,  119,  118,  129,  119,
      130,  123,  132,  125,  128,  133,  135,  134,  127,  134,
      136,  137,  138,  139,  129,  140,  142,  144,  132,  147,
      142,  130,  138,  139,  133,  135,  143,  141,  146,  148,

      136,  141,  143,  137,  140,  145,  144,  150,  151,  145,
      149,  146,  147,  152,  141,  148,  153,  141,  141,  154,
      149,  156,  157,  158,  156,  159,  162,  160,  150,  151,
      165,  154,  152,  160,  170,  161,  153,  161,  163,  164,
      158,  164,  162,  157,  159,  171,  168,  172,  163,  173,
      170,  165,  168,  174,  171,  173,  175,  176,  177,  178,
      180,  181,  172,  179,  184,  183,  180,  181,  182,  176,
      182,  185,  174,  185,  184,  186,  175,  187,  188,  177,
      178,  183,  179,  187,  189,  190,  191,  193,  198,  199,
      201,  202,  204,  198,  188,  199,  186,  193,  205,  189,

      190,  206,  207,  208,  191,  210,  206,  204,  205,  211,
      201,  212,  213,  202,  214,  215,  218,  212,  208,  211,
      216,  218,  217,  219,  221,  220,  207,  210,  222,  226,
      227,  213,  217,  220,  214,  216,  228,  215,  229,  230,
      233,  236,  235,  234,  232,  230,  221,  219,  226,  222,
      232,  227,  228,  237,  243,  244,  266,  236,  238,  239,
      229,  233,  234,  235,  238,  239,  242,  240,  245,  243,
      247,  248,  242,  249,  244,  237,  240,  250,  251,  247,
      252,  253,  258,  265,  255,  257,  259,  245,  249,  248,
      255,  262,  259,  256,  252,  260,  250,  251,  254,  257,

      261,  260,  263,  253,  258,  264,  261,  246,  263,  241,
      231,  264,  268,  268,  268,  270,  270,  271,  271,  271,
      271,  225,  224,  223,  209,  203,  200,  197,  196,  195,
      194,  192,  169,  167,  166,  155,  131,  126,  121,  114,
      106,  103,   74,   67,   58,   53,   51,   50,   49,   48,
       47,   25,   18,   17,   12,   11,    7,    3,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,

      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexique.l"
#define INITIAL 0
#line 4 "lexique.l"
/*Réalisé par: EZ-ZAKKAR Mohammed && ELmoumny Azddine && Aalloul Outmane && AMAACH Amine SMI-S6*/
#include <string.h>
#include "syntaxeY.h"
char valIdentif[50];
char valtype[50];
char  strval[50];
char val[50];
#line 655 "lexique.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 15 "lexique.l"



#line 810 "lexique.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 268 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 559 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 18 "lexique.l"
{ /* rien */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "lexique.l"
{ /*  yylval= atoi(yytext); */strcpy(val,yytext); return ENTIER; };
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 21 "lexique.l"
{ /* valReel = atof(yytext); */strcpy(val,yytext); return REEL; };
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "lexique.l"
{ strcpy(val,yytext); return CHAR; };
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "lexique.l"
{ strcpy(val,yytext); return STRING; };
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "lexique.l"
{ strcpy(valIdentif, yytext);strcpy(strval, yytext);strcpy(val, yytext); return ARRAY; };
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 25 "lexique.l"
{ return VAUT; };
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 "lexique.l"
{ strcpy(valtype, "int"); return ENTIERTYPE; };
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 "lexique.l"
{ strcpy(valtype, "float"); return REELTYPE; };
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 28 "lexique.l"
{ strcpy(valtype, "char"); return CHARTYPE; };
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 29 "lexique.l"
{ strcpy(valtype, "char *"); return STRINGTYPE; };
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 30 "lexique.l"
{ return BREAK; };
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 32 "lexique.l"
{ return CONST; };
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 33 "lexique.l"
{ return VAR; };
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 "lexique.l"
{ return WHILE; };
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "lexique.l"
{ return FINWH; };
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "lexique.l"
{ return DO; };
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "lexique.l"
{ return SI; };
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "lexique.l"
{ return SINON; };
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "lexique.l"
{ return ALORS; };
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "lexique.l"
{ return FINSI; };
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 "lexique.l"
{ return SWITCH; };
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 42 "lexique.l"
{ return FINSW; };
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 43 "lexique.l"
{ return REP; };
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 44 "lexique.l"
{ return JUS; };
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 45 "lexique.l"
{ return POUR; };
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 46 "lexique.l"
{ return FINPOUR; };
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 "lexique.l"
{ return RETURN; };
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "lexique.l"
{ return EGAL; };
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "lexique.l"
{ return DIFF; };
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "lexique.l"
{ return AFFECT; };
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "lexique.l"
{ return PLUS;};
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "lexique.l"
{ return MUL;};
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "lexique.l"
{ return DIV;};
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "lexique.l"
{ return SSTRA;};
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "lexique.l"
{ return MOD;};
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "lexique.l"
{ return ET;};
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "lexique.l"
{ return OU;};
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "lexique.l"
{ return Sup;};
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "lexique.l"
{ return Inf;};
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "lexique.l"
{ return SupEQ;};
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "lexique.l"
{ return InfEQ;};
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "lexique.l"
{ return PTVIRG;};
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 66 "lexique.l"
{ return INPUT;};
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 67 "lexique.l"
{ return OUTPUT;};
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 69 "lexique.l"
{ return FUN;};
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "lexique.l"
{ return PROC;};
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 72 "lexique.l"
{ return Algo;};
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 73 "lexique.l"
{ return Debut ; };
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 74 "lexique.l"
{ return Fin; };
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 76 "lexique.l"
{ strcpy(valIdentif, yytext);strcpy(strval, yytext);strcpy(val, yytext);  return IDENTIF; };
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 77 "lexique.l"
{ strcpy(valIdentif, yytext);return Comment;};
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 78 "lexique.l"
{ return yytext[0]; };
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 80 "lexique.l"
ECHO;
	YY_BREAK
#line 1171 "lexique.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 268 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 268 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 267);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 80 "lexique.l"


/* int valNombre;
int yylval;
float valReel; */

/* 
int yywrap(void) {
    return 1;
} */